### ISSUE TITLE
Failed to upgrade to database version 17

### ISSUE THREAD

**Issue by qoheniac** [dino/dino#1044]
Since updating Dino from 0.1.1 to 0.2.0 it crashes at start with these messages:
```
(dino:13494): CRITICAL **: 16:32:19.221: table.vala:174: Qlite Error: Add columns for version: SQLite error: 1 - duplicate column name: read_up_to_item

(dino:13494): libdino-ERROR **: 16:32:19.223: database.vala:398: Failed to upgrade to database version 17: SQLite error: 1 - index contentitem_conversation_hide_localtime_time_idx already exists
```

Edit: Same problem if I build Dino from the master branch. I can use Dino if I delete/move `~/.local/share/dino`, <s>but is there maybe a solution to this problem without loosing all of my data?</s> (I now deleted it because I don't care so much about old messages)

**Comment by fiaxh** [comment]
I assume you upgraded, downgraded and upgraded your Dino again version at some point? That can mess up the database. I pushed a commit that should make the database upgrading routine more robust to up-down-up-grading (e92ed27317ae398c867c946cf7206b1f0b32f3b4) in that specific case. In case you didn't actually delete `~/.local/share/dino` but only moved it away, you should be able to use your old state again now.

**Comment by qoheniac** [comment]
Yes, my distribution had an older version and I wanted to check if another bug still exists in the master branch and built it myself (it didn't). I then removed my own build and kept on using the distributions built and forgot about it. Some time late the distribution updated Dino and the trouble began. I think I should have made a backup of `~/.local/share/dino` before using my build and switch back to the backup after testing. Anyway, it works now. Thank you!
