### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by zuglufttier** [dino/dino#178]
Now that the Librem 5 got funded (https://puri.sm/shop/librem-5/), there might be a demand in the near future for a xmpp client that works on a small screen.

**Comment by tophazus** [comment]
Not only Librem 5. There are people using Gajim on PocketCHIP (https://getchip.com/pages/pocketchip) with 480x272 pixels and the Pyra (https://pyra-handheld.com/) will also be ready soon™. There is a lot of demand for "small screen".

**Comment by tigre-bleu** [comment]
Messages app for Gnome has some great mockups for messaging application on phones. See here: https://gitlab.gnome.org/Community/Design/app-mockups/blob/master/messages/messages.png

**Comment by dos1** [comment]
In order to implement a responsive UI, Dino would just have to use appropriate widgets from the libhandy library: https://source.puri.sm/Librem5/libhandy

**Comment by zuglufttier** [comment]
There are test image for the Librem 5 available: https://developer.puri.sm/Librem5/Development_Environment/Boards/qemu.html

So one could try to get things running already ;) First test made dino start but I couldn't even start one chat. Don't know what exactly happened as the whole VM became unresponsive.

**Comment by dos1** [comment]
Running is not an issue. The UI is ;)

![Screenshot_20190717_163857](https://user-images.githubusercontent.com/126204/61384727-74935080-a8b1-11e9-8f0d-1a7b39a5d50e.png)

**Comment by zuglufttier** [comment]
Yes... And I don't understand why Purism insisted to develop their own XMPP client... It will takes months or maybe years to implement all the features. Dino is now in a pretty good working state, I think.

**Comment by ericschdt** [comment]
I would love to see a mobile Dino version for the PinePhone, which is now shipping and slowly creates a real demand for a good XMPP client on Linux phones. ;)

**Comment by mar-v-in** [comment]
I started initial work on using libhandy in Dino for a better mobile UI. Feel free to try it out from the [feature/handy branch](https://github.com/dino/dino/tree/feature/handy).

**Comment by thibaultamartin** [comment]
For anyone interested, the main window has been made adaptive, and [here's a recording of the app being resized and used at mobile size](https://mamot.fr/@thibaultamartin/103829274414213063).

Thanks a lot for tackling that issue, it's going to be a bliss on mobile!

**Comment by masipcat** [comment]
Any ETA of this on master? Looks awesome!

**Comment by singpolyma** [comment]
I am now using dino as my main IM client on pinephone (under sxmo / postmarketOS).  It works pretty great as-is, though it has a papercut that I cannot close a conversation without trying to very quickly tap to make the hidden "X" show up, then tap again to close.  Would be nice if the "X" just always showed.

Related to running on mobile, idle CPU usage seems high.  Idle GPU for Gajim on my pinephone is close to 0, but for dino is always at least 2%, often as much as 5 or 7%.  This obviously doesn't help the already bad battery situation for my poor device...

**Comment by dos1** [comment]
For what it's worth, [libhandy 0.90.0](https://download.gnome.org/sources/libhandy/0.90/) has just been released with stable API :)

**Comment by dos1** [comment]
...and now there's [libhandy 1.0](https://download.gnome.org/sources/libhandy/1.0/) as well

**Comment by derlaft** [comment]
Some juicy screenshots from the branch `feature/handy`: 

* [dino-3](https://user-images.githubusercontent.com/852606/93654605-aad0e080-fa1e-11ea-90ad-687116faa7f5.png)
* [dino-1](https://user-images.githubusercontent.com/852606/93654607-ab697700-fa1e-11ea-87b1-88c0ad4735f5.png)

Thanks everyone involved for the good work!

**Comment by mimi89999** [comment]
This branch does work well on the Librem 5 QEMU, but there seems to be a race at a very specific window width, that makes it not very usable on desktop. See https://github.com/dino/dino/issues/731#issuecomment-621127548.

**Comment by mimi89999** [comment]
Hello,
I rebased the handy branch and ported to handy 1.0. https://github.com/mimi89999/dino/tree/handy
@mar-v-in You can pull changes to your branch and even squash out my commit.

**Comment by esu23** [comment]
Related to this topic, there is a project from Purism in which you can vote to support Dino: https://puri.sm/fund-your-app/

**Comment by mar-v-in** [comment]
@esu23 FYI, Purism's "Fund Your App" campaign is a fundraiser for Purism. If you donate and vote for Dino there, I wouldn't expect any of the donation to be actually used directly for Dino. However, Purism is contributing to GTK, libhandy and other libraries and such contributions may become beneficial to Dino. No Purism representative contacted us prior to including the Dino logo on that page.

**Comment by craftyguy** [comment]
@mar-v-in I have been testing @mimi89999's branch on my pinephone (running postmarketOS), and it's quite functional. There are only a couple of windows I've found that don't fit: the initial window that comes up to log in, and the settings window

It's really nice having OMEMO and working file transfer, and see value in merging their changes (or something close to it) soon so that this app is somewhat usable on smaller displays. I'd be more than happy to test anything else and/or include screenshots, etc. Let me know if I can help.


Screenshot:
<details>

![20201121_21h12m27s_grim](https://user-images.githubusercontent.com/1474209/99895767-c8990c80-2c3e-11eb-888d-46b13435fbd6.png)

</details>

**Comment by fiaxh** [comment]
@mimi89999 I merged your commit into the [feature/handy](https://github.com/dino/dino/tree/feature/handy) branch and updated the branch to the current master.

If someone has additions for the [feature/handy](https://github.com/dino/dino/tree/feature/handy) branch in the future: It is possible to open PRs for branches other than the master. In github's "Open a Pull Request" dialog, just set the "base" to `feature/handy`.

**Comment by craftyguy** [comment]
@fiaxh thanks! Is there a list of what's left TODO with that branch before it is ready to merge into master (beyond the two things I found in my testing, mentioned above)? Some folks (myself included) might want to help out, and having such a list would be useful.

**Comment by mimi89999** [comment]
@craftyguy Could you please show screenshots of the windows that don't fit? For the settings window, I guess that it depends on line length of the translations. Do the account setting window and group chat details window fit?

**Comment by mimi89999** [comment]
For the settings window, I propose to use such an UI. The entire row/cell is clickable and toggles the checkbox:
![Capture d’écran du 2020-11-26 17-08-56](https://user-images.githubusercontent.com/8530546/100372988-5774a300-300a-11eb-8480-dac047e16c4a.png)

**Comment by craftyguy** [comment]
@mimi89999 

Settings window:


<details>

![20201126_21h59m45s_grim](https://user-images.githubusercontent.com/1474209/100416340-1349c880-3033-11eb-992a-c4aa1cbaf6ac.png)

</details>


And account details window:

<details>

![20201126_22h00m07s_grim](https://user-images.githubusercontent.com/1474209/100416334-0fb64180-3033-11eb-9c88-df58be2221fd.png)

</details>

**Comment by mimi89999** [comment]
@craftyguy The first screenshot is not the settings window, but the contact details window. Anyway, it should be fixed in https://github.com/dino/dino/pull/948. Please test.

**Comment by esu23** [comment]
Thanks @mimi89999 for your work! [#948](https://github.com/dino/dino/pull/948) and [#949](https://github.com/dino/dino/pull/949) look great! Now the screen fits perfect.

I attach some screenshots:

<details>

<summary>Contact details</summary>

![contact_details](https://user-images.githubusercontent.com/20012803/100479137-97608680-30ed-11eb-9e2e-77af223208e1.png)

</details>


<details>

<summary>Select contact dialog</summary>

![contacts](https://user-images.githubusercontent.com/20012803/100479447-8c5a2600-30ee-11eb-9254-95796d6683e2.png)


</details>

They also look good to me in landscape mode.

**Comment by craftyguy** [comment]
@mimi89999 I can also confirm that #948 looks good, thanks!

I found a couple more windows that don't fit:

<details><summary>join channel</summary>

![20201127_11h36m26s_grim](https://user-images.githubusercontent.com/1474209/100480016-ed5d0c00-30a4-11eb-9a54-42812a23d46f.png)


</details>

<details><summary>start conversation</summary>

![20201127_11h32m54s_grim](https://user-images.githubusercontent.com/1474209/100480013-e9c98500-30a4-11eb-81c8-52efaa2e8fea.png)


</details>

**Comment by mimi89999** [comment]
@craftyguy Those are already fixed in #949.

**Comment by esu23** [comment]
With those two PRs of @mimi89999 I'd say Dino is pretty usable in Phosh.

Nevertheless, I have made a list of some dialogs that still have some minor issues:
+ Account chooser.
+ My omemo fingerprints dialog.
+ Contact's omemo fingerprints dialog.
+ Emoji chooser (The first column of emojis is not visible).
+ Group details dialog.
+ Keyboard shortcuts.

The workaround for all of them is changing into landscape mode.

**Comment by mimi89999** [comment]
Hello,
The PRs fixing join channel, start conversation and contact details were merged. The updated is now available in PostmarketOS. For users on other distributions, please check if they are using Librem's fork of GTK. It's needed for better user experience.
Please test the changes and report any issues with them and tag me.

**Comment by trymeouteh** [comment]
+1 for a Linux phone UI support!

**Comment by stealthgun** [comment]
I would like to request this aswell for the pinephone.

**Comment by mimi89999** [comment]
@trymeouteh and @stealthgun please vote on the issue instead of adding comments. It only adds noise. Please delete or hide the comment after voting.

**Comment by TRSx80** [comment]
After a bit of looking around, it appears that I will need to build from source on this feature/handy branch, in order to see how this works, have I got that right?

I had installed straight from repo in Manjaro KDE (what came on my PinePhone) but that was apparently regular desktop version.

**Comment by craftyguy** [comment]
@TRSx80 ya it's a separate branch, not released. Some distros have packaaged it though (postmarketOS).

**Comment by normandc** [comment]
Hi,
Hope it's OK to post here. I tried compiling the feature/handy branch on a Pinephone running Mobian, but the build fails. Any help to make this working appreciated. Thanks.

https://gist.github.com/normandc/f6896d2620e717dd62bab4563cab24cf#file-dino-feature-handy-failed-build-txt-L87

**Comment by normandc** [comment]
@fiaxh thanks! I compiled successfully. Now I have an issue with make install (checkinstall actually) but that's not relevant here. There are still a few screens that aren't adapted to mobile, and some issues on Pinephone which I don't know if they're related. For example, it's not possible to open an image attachment.

**Comment by TRSx80** [comment]
Finally I had some time to give this a try.  Attempting to compile directly on the PinePhone, running Mobian.

I had to install the following additional packages to get past `./configure` step:
```
ninja-build libhandy-1-dev gettext libsignal-protocol-c-dev
```
Well, I guess `ninja-build` is optional, but anyway, carrying on...

Doing `make` threw a lot of warnings, but it did seem to complete.  Executing `echo $?` immediately after returned `0` for instance.  And I can do `build/dino` and the program launches (I have not done much more than launch it at this point).

However I seemed to have some trouble installing.  Like @normandc I also used `checkinstall`.  After doing that, I can see the Dino icon in the launcher (phosh) but pressing it does nothing.  Trying to launch the binary from terminal with `/usr/local/bin/dino` returns the following error:

> error while loading shared libraries: libdino.so.0: cannot open shared object file: No such file or directory

So (perhaps naively?) I tried to install `dino-im-common` package on Debian, but this did not seem to help any.

I figured I better stop now before digging the hole any deeper, as after all I am only low to mid-level wizard at best.  :wink:  Any tips would be greatly appreciated.

**Comment by pizdjuk** [comment]
can somebody release the package for mobian?

**Comment by stealthgun** [comment]
> can somebody release the package for mobian?

You can build it yourself.

```
pinephone /var/tmp # emerge --ask media-gfx/qrencode net-libs/libsignal-protocol-c
pinephone /var/tmp # wget https://github.com/dino/dino/archive/refs/heads/feature/handy.zip
pinephone /var/tmp # unzip handy.zip 
pinephone /var/tmp # cd dino-feature-handy/
pinephone /var/tmp # ln -s /usr/bin/valac-0.48 /usr/bin/valac
pinephone /var/tmp/dino-feature-handy # ./configure --prefix=/usr/
pinephone /var/tmp/dino-feature-handy # make
pinephone /var/tmp/dino-feature-handy # make install
```

**Comment by spaetz** [comment]
> can somebody release the package for mobian?

Sorry for posting in this tracker, saying this with my informal Mobian hat on: But given that Debian has Dino 0.2.1+git20210824.93e2e0d-1 and Mobian does not try to duplicate efforts with Debian, I doubt that Mobian will carry an adapted and unreleased (thus unblessed) version of Dino from some branch that is not the release branch. The effort would rather go into getting a new release into Debian proper once a release with mobile-friendly patches is out.

**Comment by TRSx80** [comment]
I guess I became convinced by the sensible stance advocated by Mobian project, after all such stances are why I am Debian (and Mobian) user and supporter in the first place.  :)

Therefore sounds like the way forward will be to adapt the few remaining screens to mobile in a way that the main developers are pleased enough with to eventually actually merge and release this branch.

I am going on holiday in about a week, for about another week, I guess at some point after that I will try and dig into this remaining development.  But be warned I am new to it and it will take me some time to find my way.  Anyone else is of course welcome to beat me to it in the meantime.  ;)

Cheers!

**Comment by fiaxh** [comment]
The `feature/handy` branch exists to experiment with the mobile form-factor for Dino and for people to self-compile and make first tests. However, the branch won't be merged into master, as it uses libhandy. libhandy is a GTK3 library and won't be ported to GTK4. Instead, for GTK4 there will be libadwaita that can be used for mobile UIs and that also adds other widgets that we likely want to use in Dino. If we'd put in the effort to finalize a mobile UI with libhandy now, we'd have redo a bunch of effort when switching to GTK4+libadwaita - I don't think that makes sense for us.

After libadwaita 1.0 is realeased, we want to change Dino to use GTK4 and libadwaita. When that happens we can implement a mobile UI with libadwaita.

**Comment by spaetz** [comment]
Understandable. However, guven that libadwaita is basically a renamed continuation of libhandy, much of the work being done here might still be applicable in gtk4/libadwaita.

**Comment by Spirk-Stan** [comment]
If you have auto-accept disabled for a contact and a new fingerprint comes up for them, the window ends up wider than the screen until the fingerprint is accepted. Once accepted, it properly displays.

A separate issue is the overall UI is too large when the phone is oriented horizontally. It's not a big deal right now, but it will be when the Pinephone's keyboard attachment is released.

**Comment by pravi** [comment]
Just to note, Dino with libhandy is available in Debian experimental and I am using on my Librem 5 (just added official Debian repos on my pure os). It is working well so far, though calls button is not visible on mobile (on laptop same version works). Thanks a lot to everyone who made this possible.

**Comment by Maryjane-ai** [comment]
> After libadwaita 1.0 is realeased, we want to change Dino to use GTK4 and libadwaita. When that happens we can implement a mobile UI with libadwaita.

@fiaxh Libawaita 1.0 was released today: https://blogs.gnome.org/alexm/2021/12/31/libadwaita-1-0/

**Comment by TRSx80** [comment]
I have not been able to get it to work since switching my PinePhone (running Mobian) to Bookworm.  It seems to compile, but then crashes with some GTK errors when I try to run it.  Which is much more typical experience whenever trying to compile pretty much anything for this low level wizard (lol) which is why I did not bother reporting it sooner (also this is totally experimental, I do not expect support, etc.).

Maybe I should just switch to Debian Sid as pravi mentioned.  I would really rather stay on Testing (Bookworm) though.

**Comment by qstambaugh** [comment]
I've been using the flatpak version on my Pinephone running Mobian. I ran into an odd issue with opening the OMEMO fingerprint window. If there's not enough screen space for it to draw the whole window, it'll keep opening the same window indefinitely until it crashes. For now, if I need to verify a fingerprint, I have to rotate it into landscape mode so it has enough horizontal space, so it only opens one window and doesn't crash

**Comment by Neustradamus** [comment]
To follow this ticket

**Comment by fiaxh** [comment]
Most of Dinos windows and dialogs are mobile-friendly by now, so I'm closing this.

If there are more specific issues, they can be raised in dedicated issues.
