### ISSUE TITLE
Application icon on debian missing

### ISSUE THREAD

**Issue by srgcdev** [dino/dino#239]
Hello,

Since a few days ago, there is no application icon on debian anymore.

I'm using the obs package respository for debian.

Thanks in advance.

**Comment by bebehei** [comment]
I've analysed it. dino started to use the common GApplication notification system in 8fdb38b99be9c588148d576c23212af765ff7302

I tried to fix this, but I had no success. It seemed to be, that dino did not send a (raw) icon at all.

It seems, that this isn't even a problem given by dino. It seems to be a problem by the underlying vala/glib/gio.

The icon is set "properly" via the `set_icon` method. Queries an `AvatarGenerator` first to get a gdk `Pixbuf` and then converts it to an Icon.

https://github.com/dino/dino/blob/0102abeec1d2055b19dccbb7edc7f06e527642b1/main/src/ui/notifications.vala#L96

https://github.com/dino/dino/blob/0102abeec1d2055b19dccbb7edc7f06e527642b1/main/src/ui/notifications.vala#L126-L130

As Vala just gets transpiled to a C program, the GLib docs for the C language apply, too. 

So, what does [`g_notification_set_icon`](https://developer.gnome.org/gio/stable/GNotification.html#g-notification-set-icon) want? It consumes a [`GIcon`](https://developer.gnome.org/gio/stable/GIcon.html):

> GIcon does not provide the actual pixmap for the icon as this is out of GIO's scope,

**Comment by bebehei** [comment]
[The corresponding bugreport](https://bugzilla.gnome.org/show_bug.cgi?id=745698).

**Comment by fiaxh** [comment]
This issue was originally about the application icon, not about icons in notifications. The original issue should be fixed in current builds. I opened a dedicated issue (#286) for the notification icon problem.

**Comment by stevenroose** [comment]
I still don't see an application icon.. I built on Arch Linux.

**Comment by WPFilmmaker** [comment]
@fiaxh I assume we are talking about systrain icon here....if so I don't see it either, Lubuntu 18.04, Dino 0.0~git622.20200102.067184f.
